In [2]:
import torch

In [27]:
matrix = torch.tensor([[1, 2 ,3], [4, 5, 6], [7, 8 ,9]])

In [42]:
matrix.shape, matrix.dtype

(torch.Size([3, 3]), torch.int64)

In [29]:
matrix.ndim

2

In [30]:
matrix[2]

tensor([7, 8, 9])

In [31]:
a = torch.range(start = 1, end = 10, step = 1)
a

C:\Users\sachi\AppData\Local\Temp\ipykernel_6932\3597147264.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(start = 1, end = 10, step = 1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
b = torch.ones_like(a)
b

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
some_tensor = torch.tensor([1,2,3])
some_tensor.device, some_tensor.dtype, some_tensor.shape

(device(type='cpu'), torch.int64, torch.Size([3]))

In [46]:
torch.max(some_tensor), torch.argmax(some_tensor)

(tensor(3), tensor(2))

In [8]:
a1 = torch.rand(size=(6, 9))
a2 = torch.rand(size=(6, 9))

a1, a2

(tensor([[0.5801, 0.6944, 0.4637, 0.3552, 0.5904, 0.3132, 0.8770, 0.4225, 0.5876],
         [0.5613, 0.6326, 0.7061, 0.6815, 0.5500, 0.9147, 0.9507, 0.7185, 0.1160],
         [0.6201, 0.2842, 0.7041, 0.5274, 0.2634, 0.1613, 0.2518, 0.6885, 0.6893],
         [0.7017, 0.4420, 0.2780, 0.9372, 0.1785, 0.7181, 0.5127, 0.9696, 0.6399],
         [0.3216, 0.0515, 0.2771, 0.7418, 0.5216, 0.1465, 0.1842, 0.9592, 0.5541],
         [0.9518, 0.5152, 0.2274, 0.1221, 0.0076, 0.8427, 0.7475, 0.2686, 0.3691]]),
 tensor([[0.6617, 0.6512, 0.6921, 0.6976, 0.2181, 0.2752, 0.2186, 0.3108, 0.1614],
         [0.9144, 0.6216, 0.8829, 0.9024, 0.6516, 0.2778, 0.0622, 0.4343, 0.8238],
         [0.2796, 0.0557, 0.0872, 0.2755, 0.2021, 0.1704, 0.8159, 0.6825, 0.3963],
         [0.7429, 0.4271, 0.1854, 0.5407, 0.5301, 0.5683, 0.7403, 0.3601, 0.0152],
         [0.0926, 0.8811, 0.2085, 0.4563, 0.4155, 0.2379, 0.9651, 0.8811, 0.0926],
         [0.9383, 0.3960, 0.9890, 0.5401, 0.6498, 0.4510, 0.2265, 0.2537, 0.0629]]))

In [14]:
torch.vstack([a1, a2]).shape, torch.hstack([a1, a2]).shape

(torch.Size([12, 9]), torch.Size([6, 18]))